In [84]:
import pandas as pd

In [85]:
df = pd.read_csv('used_cars_data.csv')

In [86]:
df

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

In [87]:
df.isna().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

In [88]:
# here only 7253 rows and in new_price 6247 is empy soits better to drop it

# also drop sno (no need of it , serial number)

In [89]:
# drop ----> sno
# drop ----> new_price

In [90]:
df = df.drop(columns=['S.No.', 'New_Price'])
# or
# df.drop(columns='S.No.',axis = 1, inplace = True)
# df.drop(columns='New_Price',axis = 1, inplace = True)
# df

In [91]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN
7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN
7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN
7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN
7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN

In [92]:
df.isna().sum()

Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
Price                1234
dtype: int64

In [93]:
# brand = [maruthi,hydayi,....]
# split
# df['brand'] = df['Name'].str.split().str[0]
# or

In [94]:
# apply
# lambda
# lambda argument : expression
df['Brand'] = df['Name'].apply(lambda x:x.split()[0])
# created a new column with an exisiting column ----> feature extraction

In [95]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,1.75,Maruti
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,12.50,Hyundai
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,4.50,Honda
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,6.00,Maruti
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,17.74,Audi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,Volkswagen
7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,Volkswagen
7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,Nissan
7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,Volkswagen
7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,Mercedes-Benz

In [96]:
df.dtypes

Name                     str
Location                 str
Year                   int64
Kilometers_Driven      int64
Fuel_Type                str
Transmission             str
Owner_Type               str
Mileage                  str
Engine                   str
Power                    str
Seats                float64
Price                float64
Brand                    str
dtype: object

In [97]:
# object -----> string , to calculate mean , mode or median we have to convert it into int(values)
# int,float

# here , mileage is object dtype , we have to convert it into int. 
# in order to do that , we have to remove the extra km/kg unit "26.6 km/kg"
# so we could get 26.6 as an integer

In [98]:
df['Mileage'] = df['Mileage'].str.replace(' km/kg', '')

In [99]:
df['Mileage'] = df['Mileage'].str.replace(' kmpl', '')

In [100]:
df.dtypes

Name                     str
Location                 str
Year                   int64
Kilometers_Driven      int64
Fuel_Type                str
Transmission             str
Owner_Type               str
Mileage                  str
Engine                   str
Power                    str
Seats                float64
Price                float64
Brand                    str
dtype: object

In [101]:
# to convert object into int/float , here errors = coerce means 
# it force any string value to get converted to Nan instead of raising an error
df['Mileage'] = pd.to_numeric(df['Mileage'], errors='coerce')
# or
# df['Mileage'] = df['Mileage'].astype(float)

In [102]:
df.dtypes

Name                     str
Location                 str
Year                   int64
Kilometers_Driven      int64
Fuel_Type                str
Transmission             str
Owner_Type               str
Mileage              float64
Engine                   str
Power                    str
Seats                float64
Price                float64
Brand                    str
dtype: object

In [103]:
df['Engine'] = df['Engine'].str.replace('CC','')

In [104]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998,58.16 bhp,5.0,1.75,Maruti
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.2 bhp,5.0,12.50,Hyundai
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199,88.7 bhp,5.0,4.50,Honda
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248,88.76 bhp,7.0,6.00,Maruti
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968,140.8 bhp,5.0,17.74,Audi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54,1598,103.6 bhp,5.0,NaN,Volkswagen
7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21,1197,103.6 bhp,5.0,NaN,Volkswagen
7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08,1461,63.1 bhp,5.0,NaN,Nissan
7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.20,1197,103.6 bhp,5.0,NaN,Volkswagen
7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.00,2148,170 bhp,5.0,NaN,Mercedes-Benz

In [105]:
df['Engine'] = pd.to_numeric(df['Engine'], errors = 'coerce')

In [106]:
df.dtypes

Name                     str
Location                 str
Year                   int64
Kilometers_Driven      int64
Fuel_Type                str
Transmission             str
Owner_Type               str
Mileage              float64
Engine               float64
Power                    str
Seats                float64
Price                float64
Brand                    str
dtype: object

In [107]:
df['Power'] = df['Power'].str.replace('bhp','')

In [108]:
df['Power'].value_counts()

Power
74        280
98.6      166
73.9      152
140       142
null      129
         ...
252         1
328.5       1
98.63       1
360         1
241.6       1
Name: count, Length: 386, dtype: int64

In [109]:
# to locate null
df.loc[df['Power']=='null ']

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand
76,Ford Fiesta 1.4 SXi TDCi,Jaipur,2008,111111,Diesel,Manual,First,17.80,1399.0,null,5.0,2.00,Ford
79,Hyundai Santro Xing XL,Hyderabad,2005,87591,Petrol,Manual,First,0.00,1086.0,null,5.0,1.30,Hyundai
89,Hyundai Santro Xing XO,Hyderabad,2007,73745,Petrol,Manual,First,17.00,1086.0,null,5.0,2.10,Hyundai
120,Hyundai Santro Xing XL eRLX Euro III,Mumbai,2005,102000,Petrol,Manual,Second,17.00,1086.0,null,5.0,0.85,Hyundai
143,Hyundai Santro Xing XO eRLX Euro II,Kochi,2008,80759,Petrol,Manual,Third,17.00,1086.0,null,5.0,1.67,Hyundai
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6891,Toyota Etios GD,Kolkata,2013,60000,Diesel,Manual,First,23.59,1364.0,null,5.0,NaN,Toyota
6896,Toyota Etios Liva GD,Hyderabad,2013,86000,Diesel,Manual,First,23.59,1364.0,null,5.0,NaN,Toyota
6947,Toyota Etios Liva G,Delhi,2012,77800,Petrol,Manual,First,18.30,1197.0,null,5.0,NaN,Toyota
7092,Hyundai Santro Xing XG AT eRLX Euro III,Coimbatore,2007,64168,Petrol,Automatic,First,17.00,1086.0,null,5.0,NaN,Hyundai
7145,Toyota Etios Liva G,Kolkata,2012,37212,Petrol,Manual,First,18.30,1197.0,null,5.0,NaN,Toyota

In [111]:
df.Power

0        58.16
1       126.20
2        88.70
3        88.76
4       140.80
         ...
7248    103.60
7249    103.60
7250     63.10
7251    103.60
7252    170.00
Name: Power, Length: 7253, dtype: float64

In [112]:
# to change null ---> empty(Nan)
# we need numpy

In [113]:
import numpy as np

In [114]:
# df['Power'] = df['Power'].str.strip()  # remove extra spaces
# df['Power'] = df['Power'].replace('', np.nan)      # replace empty strings with NaN

In [115]:
# df['Power'] = df['Power'].replace('null ', np.nan)  # replace with NaN
# or
df.loc[df.Power=='null ','Power'] = np.nan

In [116]:
# df['Power'] = pd.to_numeric(df['Power'],errors = 'coerce')
df['Power'] = df['Power'].astype(float)
# ValueError: could not convert string to float: 'null '
# here it raises an error as power column contains 
# 129 "null" written values , which is string.
# so here we have to change null to empty
# null(str) ---> empty(nan)

In [56]:
df.dtypes

Name                     str
Location                 str
Year                   int64
Kilometers_Driven      int64
Fuel_Type                str
Transmission             str
Owner_Type               str
Mileage              float64
Engine               float64
Power                float64
Seats                float64
Price                float64
Brand                    str
dtype: object

In [117]:
# At first when we checked the empty values were : Power	46
# and now we replaced 'null ' with nan value, so the empty columns increased
# And now Power 175
df.isna().sum()

Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                 175
Seats                  53
Price                1234
Brand                   0
dtype: int64

In [118]:
# Mileage 2  -----> unique --> mean/median
# Engine	46 -----> unique --> mode
# Power	175  -----> unique --> mean/median
# Seats	53   -----> unique --> mode
# Price	1234 -----> unique --> mean/median

In [119]:
df['Mileage'].unique()  #based on output we can take mean/median bcoz floating point numbers

array([26.6 , 19.67, 18.2 , 20.77, 15.2 , 21.1 , 23.08, 11.36, 20.54,
       22.3 , 21.56, 16.8 , 25.2 , 12.7 ,  0.  , 13.5 , 25.8 , 28.4 ,
       20.45, 14.84, 22.69, 23.65, 13.53, 18.5 , 14.4 , 20.92, 17.5 ,
       12.8 , 19.01, 14.53, 11.18, 12.4 , 16.09, 14.  , 24.3 , 18.15,
       11.74, 22.07, 19.7 , 25.4 , 25.32, 14.62, 14.28, 14.9 , 11.25,
       24.4 , 16.55, 17.11, 22.9 , 17.8 , 18.9 , 15.04, 25.17, 20.36,
       13.29, 13.68, 20.  , 15.8 , 25.  , 16.4 , 24.52, 22.1 ,  8.5 ,
       15.1 , 16.95, 19.64, 16.5 , 18.53, 17.57, 18.  , 23.2 , 16.73,
       17.  , 13.  , 17.68, 22.7 , 16.2 , 15.26, 23.  , 19.83, 14.94,
       17.71, 14.74, 16.  , 22.32, 12.99, 23.3 , 19.15, 10.8 , 15.  ,
       22.  , 21.9 , 12.05, 11.7 , 21.21, 20.73, 24.07, 19.  , 20.58,
       19.27, 11.5 , 18.6 , 21.14, 11.05, 21.76,  7.81, 21.66, 17.2 ,
       20.63, 19.4 , 14.8 , 26.  , 20.4 , 21.5 , 15.3 , 17.9 , 16.6 ,
       22.54, 25.44, 13.7 , 22.48, 12.9 , 19.98, 21.4 , 19.81, 15.4 ,
       25.47, 19.87, 17.45, 14.7 , 15.64, 15.73, 23.59, 16.1 , 27.4 ,
       20.46, 15.29, 20.51, 11.8 , 14.3 , 14.67, 17.19, 21.03, 22.5 ,
       16.82, 11.72, 17.4 , 17.05, 24.  , 28.09, 20.5 , 13.1 , 19.91,
       18.7 , 16.38, 11.57, 17.3 , 22.95, 18.88, 23.4 , 22.74, 12.07,
       17.1 , 18.48, 16.47, 23.1 , 14.07, 16.02, 19.3 , 17.7 ,  9.52,
       14.75, 26.3 , 11.3 , 21.12, 21.02, 14.45, 19.33, 13.8 , 24.7 ,
       11.  , 11.07, 21.43, 14.21, 18.86, 16.07, 13.49, 20.38, 12.  ,
       17.01, 13.2 , 20.37, 15.96, 14.16, 13.17, 27.62, 25.1 , 15.17,
       11.33, 17.92, 12.55, 12.6 , 17.72, 18.16, 15.68, 15.5 , 12.1 ,
       14.83, 17.6 , 14.6 , 14.66, 10.93, 20.68,  9.9 , 21.13, 20.14,
       19.2 , 27.3 , 16.36, 26.59, 12.5 , 13.6 , 15.06, 10.13, 17.21,
       15.97, 10.5 , 14.69, 23.9 , 19.1 , 21.27, 15.9 , 20.7 , 14.1 ,
       20.89, 18.12, 12.3 , 19.71,  9.43, 13.4 , 13.14, 18.1 , 22.77,
       14.49, 12.39, 10.91, 20.85, 15.63, 27.39, 18.3 , 16.78, 25.5 ,
       10.  , 13.73, 24.2 , 14.02, 26.83, 16.77, 24.5 , 20.34, 21.7 ,
        9.7 , 14.33, 21.64, 19.16, 16.93,  9.  , 26.2 , 16.3 , 12.62,
       20.64, 14.24, 18.06, 10.2 , 10.1 , 18.25, 13.93, 25.83,  8.6 ,
       13.24, 17.09, 23.84,  8.45, 19.6 , 19.5 , 20.3 , 16.05, 11.2 ,
       27.03, 18.78, 12.35, 14.59, 17.32, 14.95, 13.22, 23.03, 33.44,
       15.6 , 19.12, 10.98, 33.54, 16.46, 18.4 , 11.1 , 13.01, 18.8 ,
       16.52, 18.44, 19.49, 23.5 , 23.8 , 12.65, 20.65, 21.72, 12.19,
       26.1 , 18.33, 12.81, 17.06, 17.67, 19.34,  8.3 , 16.96, 11.79,
       20.86, 16.98, 11.68, 15.74, 15.7 , 18.49, 10.9 , 19.59, 11.4 ,
       13.06, 21.  , 15.15, 16.9 , 18.23, 17.16, 17.43, 19.08, 18.56,
       11.9 , 24.6 , 21.79, 12.95, 25.6 , 13.45, 26.21, 13.58, 16.25,
       10.4 , 17.44, 22.71, 17.54, 15.87,  9.5 , 11.56, 14.39, 19.09,
       17.85, 31.79, 18.18, 21.19, 21.8 , 15.42, 14.47, 19.69, 12.83,
        8.  , 22.8 , 12.63, 14.57, 27.28, 15.41, 32.26, 18.19, 13.33,
       16.7 , 17.84, 23.19, 11.49, 18.51, 13.44,  8.7 ,  8.77, 17.97,
       23.57, 12.37,  9.1 , 12.51, 19.44, 21.38, 16.51, 24.8 , 14.42,
       26.8 , 24.04,  9.8 , 19.68, 21.2 , 19.72, 14.2 , 12.98, 23.01,
       16.12,  9.3 , 15.85,   nan, 17.88, 10.6 , 11.78,  7.94, 25.01,
        8.1 , 13.9 , 11.62, 20.62, 15.11, 10.37, 18.59,  9.74, 14.81,
        8.2 , 12.97,  7.5 , 30.46,  6.4 , 12.85, 18.69, 17.24, 13.07,
       12.2 , 20.8 , 11.88, 12.08, 15.56, 14.5 , 17.15])

In [120]:
df['Mileage'] = df['Mileage'].fillna(df['Mileage'].mean())

In [121]:
df.isna().sum()

Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 0
Engine                 46
Power                 175
Seats                  53
Price                1234
Brand                   0
dtype: int64

In [122]:
df['Engine'].unique()  #here also we can use mode (here it is not float)

array([ 998., 1582., 1199., 1248., 1968.,  814., 1461., 2755., 1598.,
       1462., 1497., 2179., 2477., 1498., 2143., 1995., 1984., 1197.,
       2494., 1798., 2696., 2698., 1061., 1198., 2987.,  796.,  624.,
       1999., 1991., 2694., 1120., 2498.,  799., 2393., 1399., 1796.,
       2148., 1396., 1950., 4806., 1998., 1086., 1193., 2982., 1493.,
       2967., 2993., 1196., 1799., 2497., 2354., 1373., 2996., 1591.,
       2894., 5461., 1595.,  936., 1997.,   nan, 1896., 1390., 1364.,
       2199.,  993.,  999., 1405., 2956., 1794.,  995., 2496., 1599.,
       2400., 1495., 2523.,  793., 4134., 1596., 1395., 2953., 1586.,
       2362., 1496., 1368., 1298., 1956., 1299., 3498., 2835., 1150.,
       3198., 1343., 1499., 1186., 1590., 2609., 2499., 2446., 1978.,
       2360., 3436., 2198., 4367., 2706., 1422., 2979., 1969., 1489.,
       2489., 1242., 1388., 1172., 2495., 1194., 3200., 1781., 1341.,
       2773., 3597., 1985., 2147., 1047., 2999., 2995., 2997., 1948.,
       2359., 4395., 2349., 2720., 1468., 3197., 2487., 1597., 2771.,
         72., 4951.,  970., 2925., 2200., 5000., 2149., 5998., 2092.,
       5204., 2112., 1797., 2000., 1795., 3696., 1389.])

In [123]:
df['Engine'] = df['Engine'].fillna(df['Engine'].mode())[0]

In [124]:
df.isna().sum()

Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 0
Engine                  0
Power                 175
Seats                  53
Price                1234
Brand                   0
dtype: int64