In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Iris.csv')

In [3]:
# 1. Find the number of samples in each category of species
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [4]:
# 2. Find the category that it have largest petal length
# df.groupby('Species')['PetalLengthCm'].mean().idxmax()

df.groupby('Species')['PetalLengthCm'].max().tail(1)

Species
Iris-virginica    6.9
Name: PetalLengthCm, dtype: float64

In [6]:
# 3. Drop the column 'id'
df.drop(columns = ['Id'])

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
# 4. Find the largest sepal length in each category of species
# df.loc[df.groupby(by = 'Species')['SepalLengthCm'].idxmax(), ['Species','SepalLengthCm']]

df.groupby('Species')['SepalLengthCm'].max()

Species
Iris-setosa        5.8
Iris-versicolor    7.0
Iris-virginica     7.9
Name: SepalLengthCm, dtype: float64

In [8]:
# 5. Arrange the data frame in the descending order of sepal length
df.sort_values('SepalLengthCm',ascending=False)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
131,132,7.9,3.8,6.4,2.0,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
...,...,...,...,...,...,...
41,42,4.5,2.3,1.3,0.3,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa

In [9]:
# 6. Check is there any missing value
df.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64